# Generated by Django 4.1.2 on 2023-07-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
