# Generated by Django 4.1.2 on 2023-07-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='facebook_hesabi_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter_hesabi_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
