# Generated by Django 4.1.2 on 2023-08-05 10:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='solution',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
