# Generated by Django 4.1.2 on 2023-08-05 10:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answer_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='solution',
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
