# Generated by Django 4.1.2 on 2023-08-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_answer_solution_question_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
