# Generated by Django 4.1.2 on 2023-08-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
