# Generated by Django 4.1.2 on 2023-08-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_question_img_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='img',
        ),
        migrations.AddField(
            model_name='answer',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
