# Generated by Django 4.1.2 on 2023-08-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_question_img_answer_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='img',
        ),
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
