# Generated by Django 4.1.2 on 2023-08-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
