# Generated by Django 4.1.2 on 2023-08-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_answer_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='solution',
        ),
    ]
