# Generated by Django 4.1.2 on 2023-08-12 10:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_remove_question_img_question_sual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='solution',
        ),
        migrations.AddField(
            model_name='question',
            name='hell',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
