# Generated by Django 4.1.2 on 2023-07-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='about_photo',
            field=models.ImageField(upload_to='photos/%y/%m/%d'),
        ),
    ]
