# Generated by Django 4.1.2 on 2023-07-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pages_is_published_alter_pages_about_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='is_published',
        ),
        migrations.AddField(
            model_name='pages',
            name='en_sonuncu',
            field=models.BooleanField(default=False),
        ),
    ]
