# Generated by Django 4.1.2 on 2023-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_pages_is_published_pages_en_sonuncu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='about_description',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='about_photo',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='en_sonuncu',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='last_chane',
        ),
        migrations.AddField(
            model_name='pages',
            name='haqqimizda_basliq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='haqqimizda_photo',
            field=models.ImageField(null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='pages',
            name='haqqimizda_text',
            field=models.TextField(null=True),
        ),
    ]
