# Generated by Django 4.1.2 on 2023-07-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_pages_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='instagram_hesabi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='twitter_hesabi',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
