# Generated by Django 4.1.2 on 2023-07-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_pages_instagram_hesabi_pages_twitter_hesabi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='instagram_hesabi',
            new_name='facebook_hesabi_url',
        ),
        migrations.RenameField(
            model_name='pages',
            old_name='twitter_hesabi',
            new_name='instagram_hesabi_url',
        ),
        migrations.AddField(
            model_name='pages',
            name='twitter_hesabi_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
