# Generated by Django 4.1.2 on 2023-07-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_lecture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Lecture',
            new_name='ContactLecture',
        ),
    ]
