# Generated by Django 4.1.2 on 2023-08-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_quiz_required_score_to_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='qiymet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
