# Generated by Django 4.1.2 on 2023-08-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_quiz_tarix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='qiymet',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
