# Generated by Django 4.1.2 on 2023-08-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_alter_quiz_qiymet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='topic',
            new_name='kateqoriya',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='qiymet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
