# Generated by Django 4.1.2 on 2023-08-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0007_alter_quiz_qiymet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='qiymet',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
