# Generated by Django 4.1.2 on 2023-08-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0008_alter_quiz_qiymet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='qiymet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
