# Generated by Django 4.1.2 on 2023-08-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0009_alter_quiz_qiymet'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
