# Generated by Django 4.1.2 on 2023-08-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0010_quiz_quiz_id_quiz_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user_id',
        ),
    ]
