# Generated by Django 4.1.2 on 2023-07-09 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0003_teacher_instagram_hesabi_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=150)),
                ('kateqoriya', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('tarix', models.DateField(blank=True, default=datetime.datetime.now)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher')),
            ],
        ),
    ]
