# Generated by Django 4.1.2 on 2023-07-09 22:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
